### ISSUE TITLE
Change asserts in GraphBehaviours to ShoudMatchers for more graceful test failures

### ISSUE THREAD

**Issue by pankajgupta** [twitter/cassovary#109]
A violation of an assert() statement results in a stack trace. The asserts should be removed and replaced by "shouldEqual" type statements.

cc @szymonm

**Comment by AnishShah** [comment]
Can I work on this ? @pankajgupta @szymonm

**Comment by szymonm** [comment]
No problem, it's yours.

**Comment by pankajgupta** [comment]
Might want to wait until #108 is merged

**Comment by AnishShah** [comment]
@pankajgupta cool :)

**Comment by AnishShah** [comment]
@pankajgupta Currently, scalatest is available only for test command  ```"org.scalatest" %% "scalatest" % "1.9.2" % "test"``` . We should remove ``` % "test"``` , right?

**Comment by AnishShah** [comment]
Oops sorry. I thought you wanted to remove ```assert``` from all files. Sorry.

**Comment by pankajgupta** [comment]
Fixed by @AnishShah
