### ISSUE TITLE
Cross publish Scala 2.10/2.11 releases

### ISSUE THREAD

**Issue by caniszczyk** [twitter/cassovary#126]

**Comment by caniszczyk** [comment]
I'll wait for @pankajgupta to do the honor of publishing a new release

**Comment by pankajgupta** [comment]
Thanks @caniszczyk . Noticed that there are a fair amount of 'evicted' warnings in sbt. Should we try to fix them? e.g., this one is quite frequent:
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* com.google.guava:guava:13.0.1 -> 16.0.1 (caller: com.twitter.common:collections:0.0.82, com.twitter.common:quantity:0.0.79, com.twitter:util-collection_2.11:6.23.0, com.twitter.common:util-system-mocks:0.0.81, com.twitter.common:stats-provider:0.0.66, com.twitter.common:jdk-logging:0.0.54, com.twitter.common:base:0.0.95, com.twitter.common:stats-util:0.0.49, com.twitter:finagle-http_2.11:6.24.0, com.twitter.common:stats:0.0.98, com.twitter.common:util:0.0.106, com.twitter.common:util-executor-service-shutdown:0.0.55, com.github.spullara.mustache.java:compiler:0.8.12.1, com.twitter:twitter-server_2.11:1.9.0, com.twitter.common:util-sampler:0.0.61, com.twitter:finagle-stats_2.11:6.24.0, com.twitter.common:metrics:0.0.29, com.twitter:cassovary-server_2.11:4.0.0, com.twitter:cassovary-core_2.11:4.0.0, com.twitter.common:application-action:0.0.75)

**Comment by pankajgupta** [comment]
Released, thanks @caniszczyk and @travisbrown .
