### ISSUE TITLE
Fix compilation warnings post move to scala 2.11 in cassovary version 4.0.0+

### ISSUE THREAD

**Issue by pankajgupta** [twitter/cassovary#128]
If you start working on this, please leave a comment here.

**Comment by pankajgupta** [comment]
e.g., this warning:
[warn] /Users/pankaj/work/oss/cassovary/cassovary-core/src/main/scala/com/twitter/cassovary/graph/TestGraph.scala:158: trait SynchronizedBuffer in package mutable is deprecated: Synchronization via traits is deprecated as it is inherently unreliable.  Consider java.util.concurrent.ConcurrentLinkedQueue as an alternative.
[warn]     val nodes = Array.fill[mutable.Buffer[Int]](numNodes){new ArrayBuffer[Int]() with mutable.SynchronizedBuffer[Int]}
[warn]                                                                                               ^
[warn] one warning found

**Comment by pankajgupta** [comment]
And a bunch more in tests

**Comment by AnishShah** [comment]
Working on this..
