### ISSUE TITLE
Parametrize Graph by NodeType

### ISSUE THREAD

**Issue by pankajgupta** [twitter/cassovary#143]
As @szymonm mentioned in #141 something like:

trait Graph[NodeType <: Node] {
  getNodeById: Option[NodeType]
...
}

That allows Node to be subclassed and used in the respective Graph. e.g., in #141 we would do:

trait UndirectedGraph extends Graph[UndirectedNode] {
  getNodeById: Option[UndirectedNode]
}

**Comment by AnishShah** [comment]
Working on this..
