### ISSUE TITLE
Adding cassovary as dependency does not work

### ISSUE THREAD

**Issue by bartekkalinka** [twitter/cassovary#145]
When adding cassovary as dependency in another project (according to Readme):
libraryDependencies += "com.twitter" %% "cassovary" % "4.0.0"
in build.sbt
I get compile error "object cassovary is not a member of package com.twitter".

I checked cassovary jar in Ivy repository cache and it does not contain any classes (just metainf directory).  It's the same, when I compile cassovary with sbt package - jar in target directory is empty, and there's no classes in main target directory.

Workaround is:
libraryDependencies += "com.twitter" %% "cassovary-core" % "4.0.0"

Should we modify Readme or fix the build to match Readme?

**Comment by pankajgupta** [comment]
that's a bug in README. Yes, please fix README. thanks
