### ISSUE TITLE
Remove the concept of internal/external id in BipartiteGraph

### ISSUE THREAD

**Issue by pankajgupta** [twitter/cassovary#165]
Simplify it to both LeftNode and RightNode being the same BipartiteNode and the choice of which ids belong to LHS and which ids belong to RHS left to the user. The constructor of BipartiteGraph can take in a function parameter isLeftNode: Int => Boolean that tells whether an id is for left or right side of the graph, which should be checked for neighbors of a BipartiteNode and a runtime exception thrown if a left node has another left node has a neighbor (or right node has another right node as a neighbor).
CC @AnishShah

**Comment by AnishShah** [comment]
Can we have `Map[Int, BipartiteNode]` instead of `Array[BipartiteNode]` for storing Nodes?
If you look at `getNodeById` function, 

```
val leftOriginalId = - id
if (leftOriginalId < leftNodes.length) {
  if (leftNodes(leftOriginalId) != null) Some(leftNodes(leftOriginalId))
  ...
```

If it a left node, then it first takes the positive value and then returns the node from array. We might not want to do this, right? Map would be a better idea. I guess.

**Comment by pankajgupta** [comment]
Map is just in general more inefficient than an array so lets still have an array based implementation. You could still have two separate arrays: left and right and use one or the other depending on isLeftNode function.

**Comment by AnishShah** [comment]
@pankajgupta I got that. But, `isLeftNode: Int => Boolean` allows left node to have an ID other than a negative number. Then what to do when we want to return a node by id?

First Case: I want to save positive numbers for right nodes and negative numbers for the left nodes.
`leftNode(1) = new LeftNode(-1, Array(), Array())`.
`rightNode(1) = new RightNode(1, Array(), Array())`.

Second Case: I'm saving even numbers for the right nodes and odd numbers for left nodes.
`leftNode(1) = new LeftNode(1, Array(), Array())`.
`rightNode(2) = new RightNode(2, Array(), Array())`.

Hope this makes sense?

**Comment by pankajgupta** [comment]
@AnishShah I am not sure I understand "Then what to do when we want to return a node by id?". If class BipartiteGraph just takes in a single array of nodes: Array[BipartiteNode] rather than separate leftNodes and rightNodes, will it work?

**Comment by AnishShah** [comment]
@pankajgupta I mean,`getNodeById` method currently checks for Left Node. If it is a Left Node, then it negates the id and returns the node. So, this won't work for other cases (where left node ids are not negative.).

Just a single array of nodes would work only if left nodes and right nodes will have positive and unique ids. right?

**Comment by pankajgupta** [comment]
Backing up a bit: The idea of bipartite graph class is to allow a user of that class to specify a graph which might have nodes with same id in left and right hand side, e.g., from the POV of the user, there can be edge between 1 on LHS and 1 on RHS. It is the job of the class to still work -- i.e., manage the internal ids to be unique. The current class does this fine by translating the external id to a unique internal id.

However the current class does not handle the case well when the user already has unique id across the two sides, e.g., say the user knows that id 1 and 2 are LHS nodes and ids 4 and 5 are RHS nodes. In that case there is no reason to force specification of nodes in two separate arrays and do the negation of ids trick. i.e., this class should allow a new constructor which takes in a single array of nodes along with a function isLeftNode.

**Comment by AnishShah** [comment]
@pankajgupta Sorry. I moved to a different city. Couldn't reply. 

As you said the current class does not handle the case of unique ids well. Do you want me to such the complete structure of BipartiteGraph? any suggestions..?

**Comment by pankajgupta** [comment]
May be allow the user to specify whether the ids are already unique or not?

**Comment by AnishShah** [comment]
@pankajgupta For that, we will need a different implementation for Bipartite Graph.

**Comment by AnishShah** [comment]
I'll try to implement this... will send a PR in some days..

**Comment by pankajgupta** [comment]
Great

**Comment by AnishShah** [comment]
I think, we can close this issue.

**Comment by pankajgupta** [comment]
Sure
