### ISSUE TITLE
Suddenly failing Travis CI

### ISSUE THREAD

**Issue by pankajgupta** [twitter/cassovary#180]
https://travis-ci.org/twitter/cassovary/builds shows that version with git tag 5.1.1 suddenly started failing travis ci builds, and every build since then has failed with the same message:
[error] (cassovary-core/*:update) sbt.ResolveException: unresolved dependency: com.twitter.common#metrics;0.0.29: not found

This is particularly strange since doing 
$ git diff 5.1.0 5.1.1
shows no change.

Further, I created a branch called old-state-good-travis which goes back to the tip at 5.1.0 and it now also fails Travis build. https://travis-ci.org/twitter/cassovary/builds/59096320

I'm out of ideas -- @caniszczyk : any help when you get a chance would be really appreciated.

**Comment by pankajgupta** [comment]
Created a new branch "new-travis-file" to play with different .travis.yml but doesn't seem to help. Throws the mysterious message while downloading metrics.jar. See https://travis-ci.org/twitter/cassovary/jobs/59100775
[warn] 	[FAILED     ] com.twitter.common#metrics;0.0.29!metrics.jar: The HTTP response code for http://maven.twttr.com/com/twitter/common/metrics/0.0.29/metrics-0.0.29.jar did not indicate a success. See log for more detail. (1ms)

**Comment by pankajgupta** [comment]
Wonder if this is related to http://stackoverflow.com/questions/18208224/force-sbt-to-follow-redirects-for-an-explicit-github-releases-url

**Comment by travisbrown** [comment]
Hi @pankajgupta, I've just sent you an email about this issue—it's an intermittent problem with the `maven.twttr.com` repository that needs more investigation.

**Comment by pankajgupta** [comment]
Thanks for looking into it! I didn't seem to have gotten your email. Please
resend to pankaj@yogins.com

**Comment by pankajgupta** [comment]
@travisbrown any suggested fixes apart from just including that jar in repo.

**Comment by travisbrown** [comment]
You can use `- travis_retry sbt ++$TRAVIS_SCALA_VERSION test` to make Travis retry the entire failed command three times—this has fixed the issue for us for other projects.

**Comment by caniszczyk** [comment]
@pankajgupta checking through your dependencies, why do you need something from maven.twttr.com? Can we refactor something to remove the dependency? That should help with the flakiness and in the future, maven.twttr.com will eventually go away

**Comment by travisbrown** [comment]
@caniszczyk At a glance it looks like it might not be too hard to remove the direct `com.twitter.common` dependencies here, but metrics is also needed by finagle-stats, which would be a lot harder to disentangle. We just need to start publishing this stuff to Maven Central.

**Comment by pankajgupta** [comment]
That's right. Currently, we are using finagle-stats which needs metrics.

I am not sure if retries will help. Looks like very single travis build has
failed in the last few days.

What again is the intermittent problem with maven.twttr.com -- is it
unsolvable ?

**Comment by pankajgupta** [comment]
Solved for now by doing retries.
