### ISSUE TITLE
Convert Node.inboundNodes() and outboundNodes() to have Array[Int] instead of Seq[Int]

### ISSUE THREAD

**Issue by pankajgupta** [twitter/cassovary#200]
I think @szymonm you had pointed this out with some benchmarking data as well? If so, can you please link to a gist if possible. I am finally coming around to agreeing that this should indeed be done as the current code does un-necessary boxing/unboxing.

**Comment by szymonm** [comment]
What could be event better is to have our own Seq (backed by Array) that is
specialized.

I benchmarked only some Map based boxing.

**Comment by pankajgupta** [comment]
So something like class MySeq[@specialized(Int) T] { ... }

what are the reasons using this would that be better than plain Array?

**Comment by szymonm** [comment]
If we implement get(n: Int): Int in MySeq returned int will not be boxed.
And all the other methods we implement in Seq.

**Comment by pankajgupta** [comment]
So will in an array?

**Comment by szymonm** [comment]
That's true. But I was thinking that MySeq could have API that is a subset
of scala.Seq (inluding map function for instance), so that we can
eventually change it to scala.Seq, when Scala solves boxing/unboxing
problems.

**Comment by pankajgupta** [comment]
Hey @szymonm -- just wondering if you are working on this?

**Comment by szymonm** [comment]
Yes, I am. Trying to finish CMap right now and then CSeq...
