### ISSUE TITLE
Deprecate Ostrich and use Metrics

### ISSUE THREAD

**Issue by pankajgupta** [twitter/cassovary#89]
https://github.com/twitter/ostrich is currently used to maintain internal Stats in Cassovary. Ostrich does not seem to be actively maintained. Instead, should move to https://github.com/twitter/commons/tree/master/src/java/com/twitter/common/metrics as is used in Finagle-stats (http://twitter.github.io/finagle/guide/Metrics.html) as well.

**Comment by AnishShah** [comment]
@pankajgupta I would like to work on this!

**Comment by pankajgupta** [comment]
Sure -- please go ahead

**Comment by AnishShah** [comment]
Hi, so I have started working on this..
We will need [Twitter-Server](https://twitter.github.io/twitter-server/Migration.html) integrated into `CassoveryServer.scala` instead of current Ostrict AdminHttpService. 

When I added `"com.twitter" % "twitter-server_2.10" % "1.9.0"` to `Build.scala` , I'm getting the following error. I tried a lot, but I'm not able to resolve this. Can anyone help? @pankajgupta @szymonm 

```
[error] Modules were resolved with conflicting cross-version suffixes in {file:/home/anish/ClonedProjects/cassovary/}cassovary:
[error]    com.twitter:util-jvm _2.9.2, _2.10
[error]    com.twitter:util-core _2.9.2, _2.10
[error]    com.twitter:util-logging _2.9.2, _2.10
[error]    com.twitter:util-app _2.9.2, _2.10
[error] Modules were resolved with conflicting cross-version suffixes in {file:/home/anish/ClonedProjects/cassovary/}cassovary-core:
[error]    com.twitter:util-jvm _2.9.2, _2.10
[error]    com.twitter:util-core _2.9.2, _2.10
[error]    com.twitter:util-logging _2.9.2, _2.10
[error]    com.twitter:util-app _2.9.2, _2.10
java.lang.RuntimeException: Conflicting cross-version suffixes in: com.twitter:util-jvm, com.twitter:util-core, com.twitter:util-logging, com.twitter:util-app```

**Comment by szymonm** [comment]
Can you push a PR? I can lok at it
W dniu niedz., 18 sty 2015 o 17:14 Anish Shah <notifications@github.com>
napisał(a):

**Comment by AnishShah** [comment]
Should we close this now?

**Comment by caniszczyk** [comment]
Yes IMHO
