### ISSUE TITLE
Build for Scala 2.11

### ISSUE THREAD

**Issue by chrisbeach** [twitter/cassovary#90]
Please could you release a build for Scala 2.11?

**Comment by pankajgupta** [comment]
See outstanding issue https://github.com/twitter/cassovary/issues/89 regarding Ostrich.
Migration to scalatest is tracked in https://github.com/twitter/cassovary/issues/64

**Comment by szymonm** [comment]
Including PR in review #64 is done.
We are waiting only for #89 - in progress.

**Comment by szymonm** [comment]
@AnishShah Are you currently working also on 2.11? If not, I can take care of it.

**Comment by AnishShah** [comment]
First we need to migrate from ostrich to metrics right? Currently doing
that..

**Comment by szymonm** [comment]
Right, ok.

**Comment by caniszczyk** [comment]
This is now done through a combination of commits https://github.com/twitter/cassovary/commit/9135d0d7cda38d14183bca1e10fa8e968063e466
